/*
  _____  _           _     _       _____ __  __ _____   _____        __   ___   ___  
 |  __ \(_)         | |   | |     / ____|  \/  |  __ \ / ____|      /_ | / _ \ / _ \ 
 | |  | |_ ___  __ _| |__ | | ___| |    | \  / | |  | | (___   __   _| || | | | | | |
 | |  | | / __|/ _` | '_ \| |/ _ \ |    | |\/| | |  | |\___ \  \ \ / / || | | | | | |
 | |__| | \__ \ (_| | |_) | |  __/ |____| |  | | |__| |____) |  \ V /| || |_| | |_| |
 |_____/|_|___/\__,_|_.__/|_|\___|\_____|_|  |_|_____/|_____/    \_/ |_(_)___(_)___/  
 
*/
 
# Message that occurs when player runs a disabled command - Use & or ยง to colour the text
disabled_cmd_msg: ยง4This command is disabled!
 
# The commands players can still run normally
enabled_cmds:
